### ISSUE TITLE
mouseExited gets sent to subviews that have been removed

### ISSUE THREAD

**Issue by saikat** [cappuccino/cappuccino#236] opened 2009-08-07 20:30 UTC
To recreate this issue:
1. Add view A as a subview to view B
2. Put mouse over view A
3. Remove view A from its superview
4. When you move your mouse now, view A still gets a mouseExited event

**Comment by daboe01** [comment] 2015-11-07 16:48
probably fixed by #2395

**Comment by daboe01** [comment] 2016-01-08 14:22
@didierkorthoudt was this fixed by #2395?

**Comment by didierkorthoudt** [comment] 2016-01-11 19:20
Hi @daboe01 ,

Sorry for the delay...

I've just checked and nope... viewA received mouseExited.

I check in CPTrackingArea mechanism and get back to you...

Sorry for this.

Didier.

**Comment by daboe01** [comment] 2016-01-12 18:26
Thank you for checking. Best greetings Daniel 

Von meinem iPhone gesendet

**Comment by didierkorthoudt** [comment] 2016-01-12 19:46
I've found the problem (in the CPTrackingArea). It's caused by a running condition but only (it seems) when you use the mouseEntered event to do the view removal. In other conditions, CPTrackingArea handles this correctly.

I have to adapt my code to cope with this situation. I'll do it ASAP.

**Closed** 2016-01-23 15:02 UTC
Labels: #accepted, #needs-patch, AppKit, bug
