### ISSUE TITLE
Objective-J Does Not Initialize Instance Variables

### ISSUE THREAD

**Issue by aksuska** [cappuccino/cappuccino#2569] opened 2017-11-22 18:49 UTC
Not sure if this is a compiler or runtime issue, but I noticed that instance variables are not initialized to a default value. For many expecting Objective-J to behave like Objective-C (which is the goal, after all) may get hit by difficult to test for bugs such as _instanceVar == NO. If _instanceVar is never assigned to, this expression is false, even though it is also true that: _instanceVar != YES, because _instanceVar is undefined. Objective-C-er's expect bools to be NO, numbers to be 0, and objects to be nil without having to initialize them in -init.

**Comment by mrcarlberg** [comment] 2017-11-22 20:45
All instance variables are set to null. I just tested this in our project.

Please show some code or example when this is not the case.

**Comment by aksuska** [comment] 2017-11-22 21:54
Hmm, I thought it was coming up as undefined, but I must have that wrong. Even then the issue remains as null != NO, so I would modify this to that BOOL ivars should be set to NO, and numbers to 0 (zero). This is how the objective-C runtime works, and if parity is desired, would be preferable for Objj.

**Comment by mrcarlberg** [comment] 2017-11-23 08:23
They question is if Objective-C really sets a boolean instance variable to ```false``` or ```nil```?

Objective-C is a superset of C. Objective-J is a superset of Javascript. In C ```NULL == false```. In Javascript ```null != false```. This means that we could equally say that Objective-C sets a boolean instance variable to ```nil``` which is the same as ```false``` in Objective-C but not in Objective-J.

Also it is very hard to implement:
There are no types in Javascript so there are no types in Objective-J. We can't know when to set an uninitialized instance variable to ```null``` or ```false```.

**Comment by aksuska** [comment] 2017-11-23 18:29
I understand that Objective-C sets every instance variable to 0 (zero), which is nil for a pointer (object), and since BOOLs are actually numeric, false as 0 == NO. I get that JS doesn't have scalar types of any kind, which is why null is the best choice.

I can't speak to difficulty, since I don't know how it is done, but still couldn't you just do:
     if(typeof ivar == "number" || toString.call(ivar) == '[object Number]')
          ivar = 0;
     else
          ivar = null;
?

**Comment by mrcarlberg** [comment] 2017-11-23 18:56
The problem is not that Javascript does not have scalar types in the same manner as C. It is that any variable can store any value of any type.

```typeof```will not work as Javascript does not have any types on variables, so at first ```typeof ivar``` will evaluate to ```"undefined"```. After you set it to ```NO```, ```typeof ivar``` will evaluate to ```"boolean"```.
You can even set it to ```"Foo"``` as it can be any type. Then ```typeof ivar``` will evaluate to ```"string"```

There is no way you can figure out what type it is declared as because Javascript has no types. The type for the ivar in your class declaration is only for syntax compatibility with Objective-C and documentation. It can be any string you like.

**Comment by mrcarlberg** [comment] 2018-01-05 10:02
I will close this as there are no ways (as stated above) we can figure out if an variable is a boolean or something else. Please reopen this if someone has an idea how to do this.

**Closed by mrcarlberg** 2018-01-05 10:02 UTC
